export const artistDataset = {
	'Starstuff' : 'Canada',
	'Hoodie' : 'Canada',
	'Cashforgold' : 'USA',
	'Sleep Well' : 'USA',
	'Resonata' : 'USA',
	'Djedi' : 'USA',
	'Kareful' : 'England',
	'Stohou' : 'England',
	'Skit' : 'England',
	'Fyoomz' : 'USA',
	'Martian Moon' : 'Canada',
	'Dyzphoria' : 'Canada',
	'Juche' : 'Switzerland',
	'MRKRYL' : 'Canada',
	'pinknokia' : 'USA',
	'Yedgar' : 'Canada',
	'LTHL' : 'England',
	'Barnacle Boi' : 'USA',
	'Ludicy' : 'USA',
	'Giant Ibis': 'Canada',
	'lostageless' : 'Poland',
	'TW1GZ' : 'USA',
	'KAVERN' : 'USA',
	'w/Out' : 'USA',
	'Othos' : 'USA',
	'Shxde' : 'USA',
	'AL_NE' : 'USA',
	'INFDL' : 'USA',
	'Medici' : 'USA',
	'brothel' : 'USA',
	'Sidewalks and Skeletons' : 'England',
	'MINGO' : 'USA',
	'Deadcrow' : 'Netherlands',
	'Sorsari' : 'Canada',
	'Kyddiekafka' : 'Spain',
	'Arael' : 'Canada',
	'ONHELL' : 'USA',
	'Plastician' : 'England',
	'Skeler' : 'Australia',
	'Ytho' : 'Australia',
	'Guilt Chip' : 'USA',
	'TIGEREYES' : 'USA',
	'Enjoii' : 'Poland',
	'ROILLY' : 'Belarus',
	'JessAudrey' : 'USA',
	'Calicry' : 'USA',
	'Module' : 'USA',
	'Weaver Beats' : 'USA',
	'Klimeks' : 'England',
	'Just Connor' : 'USA',
	'Sweep' : 'Sweden',
	'Eevee' : 'Netherlands',
	'Vacant' : 'England',
	'REMNANT.exe' : 'USA',
	'coldkiss' : 'USA',
	'Yama' : 'USA',
	'Unnholy' : 'Poland',
	'Kissay' : 'USA',
	'Sweeper' : 'USA',
	'WHITEMAGE' : 'Greece',
	'Svexx' : 'USA',
	'dreams47' : ''
};









